### ISSUE TITLE
Visualisation - axis labels question  

### ISSUE THREAD

**Issue by desa-la** [thegenemyers/FASTGA#3]
Hi,

Thanks for this fast and amazing tool. I have one question regarding visualisation.
I am running the following code:
`FastGA -vk $DIR3/F32.bam2fq.asm.bp.hap1.p_ctg.fa $REF/Bhaga_genome.fasta`
`ALNplot -vS F32.h1.vs.Bhaga.genome.paf`
I am doing this for many samples with same reference genome "Bhaga_genome.fasta".
When looking at the eps output files the order and labelling is a bit confusing. For example look at the chromosome with repetitive sequence in my REF genome that shifted from position 3 in B49 picture to position 5 in F32 picture on X axis. How can I have meaningful names for chromosomes or keep their order? 
Thank you very much for your time.

![B49](https://github.com/user-attachments/assets/c10695d9-5587-4364-a4cd-174b8b07e344)

![F32](https://github.com/user-attachments/assets/5934572f-e42c-4483-9177-802a31415452)

**Comment by c-zhou** [comment]
Hi @desa-la,

ALNplot arranges sequences on x-axis based on the order they appear in the PAF files which does not necessarily follow the order in the reference. There are two options. You can either rerun FastGA with '-1' option to generate '1aln' files (where the sequence order are preserved) and feed them to ALNplot, or you can still use the PAF files but need to specify the sequence order on  x-axis by providing ALNplot an extra file -  in your case, it can be something like `ALNplot F32.h1.vs.Bhaga.genome.paf @ x_order.txt` and in 'x_order.txt' you put the reference chromosome names in order, one per line, for example, `@chr1`, `@chr2`, .... The '@' sign in the command and those before chromosome names in each row in 'x_order.txt' are required. There are spaces before and after '@' in the command.

To print sequence names instead of IDs, you need to run ALNplot without '-S' option.

Best,
Chenxi

**Comment by desa-la** [comment]
Hi @c-zhou,

Great, thanks a lot for the fast answer.

best,
Desa
